/*
Author : Preeti Benake

Problem Description :
Prime numbers can also be generated by an algorithm known as the Sieve of
Erastosthenes.The algorithm for this procedure is presented here.Write a program
that implements this algorithm. Have the program find all prime numbers up to n
= 150.What can you say about this algorithm as compared to the ones used in the
text for calculating prime numbers?
Sieve of Erastosthenes Algorithm
To Display All Prime Numbers Between 1 and n
Step 1: Define an array of integers P. Set all elements Pi to 0, 2 <= i <= n.
Step 2: Set i to 2.
Step 3: If i > n, the algorithm terminates.
Step 4: If Pi is 0, then i is prime.
Step 5: For all positive integer values of j, such that i x j ≤ n, set Pixj to 1.
Step 6: Add 1 to i and go to step 3.

*/

#include<stdio.h>

int main() {

	int n=0, i=0, p[150],q[150], j=0, k=0,b=0;
	printf("The prime numbers : \n");
	


	for (i = 0; i < 150; i++) {
		if (i % 2 != 0) {
			p[j] = i;
			j++;
		}	
	}

	printf("The size of the array %d\n\n", j);
	i = 0;
	for (k = 0; k < j; k++) {
		if (p[k] % 3 != 0) {
			q[i] = p[k];
			i++;
		}
	}
	j = 0;
	for (k = 0; k < i; k++) {
		if (q[k] % 5 != 0) {
			p[j] = q[k];
			j++;
		}
	}
	

	for (i= 0; i < j; i++) {
		printf("%d \t ", p[i]);
	}



	return 0;
}